### ISSUE TITLE
Quest : Going, going, guano ! (1109)

### ISSUE THREAD

**Issue by AliziaKaline** [EverystWoW/server#3]
The quest "Going, going, guano !" shouldn't be given before the level 30.

![image](https://user-images.githubusercontent.com/12145066/33517772-5d9edb6e-d78a-11e7-940b-bf578ea62e37.png)
_(Sources : Official World of Warcraft Dungeon Companion)_

**Comment by nirelz** [comment]
http://wowwiki.wikia.com/wiki/Quest:Going,_Going,_Guano!

**Comment by Snowie493** [comment]
http://wowwiki.wikia.com/wiki/Quest:Going,_Going,_Guano!

**Comment by EverystWoW** [comment]
Fixed thank you.
